using System.Collections.Immutable;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Spire.SourceGenerator;

/// <summary>
/// Generates type-safe builder extension methods for shared resources.
/// </summary>
[Generator]
public sealed class SharedResourceGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("SharedResources.g.json"));

        var resourceEntries = jsonFiles
            .Select(static (file, ct) => file.GetText(ct)?.ToString())
            .Where(static text => text is not null);

        context.RegisterSourceOutput(resourceEntries, static (ctx, json) =>
        {
            if (string.IsNullOrWhiteSpace(json))
                return;

            var resources = JsonSerializer.Deserialize<ResourceEntry[]>(json);
            if (resources is null)
                return;

            foreach (var resource in resources)
            {
                if (string.IsNullOrEmpty(resource.Id))
                    continue;

                var name = resource.Name ?? resource.Id;
                var safeName = ToSafeIdentifier(name);
                var source = GenerateResourceSource(safeName, resource);

                ctx.AddSource($"{safeName}.g.cs", SourceText.From(source, Encoding.UTF8));
            }

            var configSource = GenerateConfigurationSource(json);
            ctx.AddSource("SharedResourcesConfiguration.g.cs", SourceText.From(configSource, Encoding.UTF8));
        });
    }

    private static string GenerateResourceSource(string safeName, ResourceEntry resource)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using Aspire.Hosting;");
        sb.AppendLine("using Aspire.Hosting.ApplicationModel;");
        sb.AppendLine("using Aspire.Hosting;");
        sb.AppendLine();

        // Interface
        sb.AppendLine($"public interface I{safeName}ResourceBuilder");
        sb.AppendLine("{");
        sb.AppendLine($"    I{safeName}ResourceBuilder ConfigureContainer(Action<IResourceBuilder<IResource>> configure);");
        sb.AppendLine($"    I{safeName}ResourceBuilder ConfigureProject(Action<IResourceBuilder<IResource>> configure);");
        sb.AppendLine($"    I{safeName}ResourceBuilder Configure<T>(Action<IResourceBuilder<T>> configure) where T : IResource;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Builder class
        sb.AppendLine($"public sealed class {safeName}ResourceBuilder : SharedResourceBuilder, I{safeName}ResourceBuilder");
        sb.AppendLine("{");
        sb.AppendLine($"    public {safeName}ResourceBuilder(IResourceBuilder<IResource> inner, ResourceMode mode)");
        sb.AppendLine("        : base(inner, mode) { }");
        sb.AppendLine();
        sb.AppendLine($"    new public I{safeName}ResourceBuilder ConfigureContainer(Action<IResourceBuilder<IResource>> configure)");
        sb.AppendLine("    {");
        sb.AppendLine("        base.ConfigureContainer(configure);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    new public I{safeName}ResourceBuilder ConfigureProject(Action<IResourceBuilder<IResource>> configure)");
        sb.AppendLine("    {");
        sb.AppendLine("        base.ConfigureProject(configure);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    new public I{safeName}ResourceBuilder Configure<T>(Action<IResourceBuilder<T>> configure) where T : IResource");
        sb.AppendLine("    {");
        sb.AppendLine("        base.Configure(configure);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Extension method
        sb.AppendLine($"public static class {safeName}ResourceExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static I{safeName}ResourceBuilder Add{safeName}(this IDistributedApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var modeValue = builder.Configuration[\"Aspire:Resources:{resource.Id}:Mode\"];");
        sb.AppendLine("        var mode = string.Equals(modeValue, \"Project\", System.StringComparison.OrdinalIgnoreCase)");
        sb.AppendLine("            ? ResourceMode.Project");
        sb.AppendLine("            : ResourceMode.Container;");
        sb.AppendLine();

        sb.AppendLine("        IResourceBuilder<IResource> inner;");
        sb.AppendLine("        if (mode == ResourceMode.Project)");
        sb.AppendLine("        {");

        if (!string.IsNullOrEmpty(resource.ProjectPath))
        {
            sb.AppendLine($"            inner = builder.AddProject<{safeName}ProjectMetadata>(\"{resource.Id}\");");
        }
        else
        {
            sb.AppendLine($"            var projectPath = builder.Configuration[\"Aspire:Resources:{resource.Id}:ProjectPath\"];");
            sb.AppendLine($"            inner = builder.AddProject(\"{resource.Id}\", projectPath);");
        }

        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");

        var image = !string.IsNullOrEmpty(resource.ContainerImage) ? resource.ContainerImage : resource.Id;
        var tag = !string.IsNullOrEmpty(resource.ContainerTag) ? resource.ContainerTag : "latest";

        if (!string.IsNullOrEmpty(resource.ImageRegistry))
        {
            sb.AppendLine($"            inner = builder.AddContainer(\"{resource.Id}\", \"{resource.ImageRegistry}/{image}\", \"{tag}\");");
        }
        else
        {
            sb.AppendLine($"            inner = builder.AddContainer(\"{resource.Id}\", \"{image}\", \"{tag}\");");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        return new {safeName}ResourceBuilder(inner, mode);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Project metadata class if project path is known at build time
        if (!string.IsNullOrEmpty(resource.ProjectPath))
        {
            sb.AppendLine();
            sb.AppendLine($"public class {safeName}ProjectMetadata : IProjectMetadata");
            sb.AppendLine("{");
            sb.AppendLine($"    public string ProjectPath => \"{resource.ProjectPath}\";");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GenerateConfigurationSource(string json)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine();
        sb.AppendLine("namespace Aspire.Hosting;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registers resolved shared resources as an in-memory JSON configuration source.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SharedResourcesConfigurationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    // lang=json");
        sb.AppendLine("    private const string SharedResourcesJson = \"\"\"");
        sb.Append("        ");
        sb.AppendLine(json.Replace("\r", ""));
        sb.AppendLine("        \"\"\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds the resolved shared resources JSON to the configuration builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IConfigurationBuilder AddSharedResourcesConfiguration(this IConfigurationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var stream = new System.IO.MemoryStream(System.Text.Encoding.UTF8.GetBytes(SharedResourcesJson));");
        sb.AppendLine("        return builder.AddJsonStream(stream);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToSafeIdentifier(string name)
    {
        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }
            else
            {
                capitalizeNext = true;
            }
        }

        return sb.ToString();
    }

    private sealed class ResourceEntry
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Mode { get; set; }
        public string ProjectPath { get; set; }
        public string ContainerImage { get; set; }
        public string ContainerTag { get; set; }
        public string BuildImageCommand { get; set; }
        public string BuildImage { get; set; }
        public string ImageRegistry { get; set; }
    }
}
