using System.Collections.Immutable;
using System.Text;
using System.Text.Json;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Spire.SourceGenerator;

/// <summary>
/// Generates type-safe builder extension methods for shared resources.
/// </summary>
[Generator]
public sealed class SharedResourceGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("SharedResources.g.json"));

        var resourceEntries = jsonFiles
            .Select(static (file, ct) => file.GetText(ct)?.ToString())
            .Where(static text => text is not null);

        context.RegisterSourceOutput(resourceEntries, static (ctx, json) =>
        {
            if (string.IsNullOrWhiteSpace(json))
                return;

            var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            var config = JsonSerializer.Deserialize<SharedResourcesConfig>(json, options);
            if (config?.Resources is null)
                return;

            foreach (var kvp in config.Resources)
            {
                var id = kvp.Key;
                var resource = kvp.Value;

                if (string.IsNullOrEmpty(id))
                    continue;

                var safeName = ToSafeIdentifier(id);
                var source = GenerateResourceSource(safeName, id, resource);

                ctx.AddSource($"{safeName}.g.cs", SourceText.From(source, Encoding.UTF8));
            }

            var configSource = GenerateConfigurationSource(json);
            ctx.AddSource("SharedResourcesConfiguration.g.cs", SourceText.From(configSource, Encoding.UTF8));
        });
    }

    /// <summary>
    /// The common interfaces implemented by both <c>ContainerResource</c> and <c>ProjectResource</c>.
    /// The generated builder class implements <c>IResourceBuilder&lt;T&gt;</c> for each of these,
    /// allowing Aspire extension methods (e.g. <c>WithEnvironment</c>, <c>WithEndpoint</c>) to work directly.
    /// </summary>
    private static readonly string[] ResourceInterfaces =
    [
        "IResourceWithEnvironment",
        "IResourceWithArgs",
        "IResourceWithEndpoints",
        "IResourceWithWaitSupport",
        "IResourceWithProbes",
        "IComputeResource",
    ];

    private static string GenerateResourceSource(string safeName, string resourceId, ResourceEntry resource)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable ASPIREPROBES001");
        sb.AppendLine();
        sb.AppendLine("using Aspire.Hosting;");
        sb.AppendLine("using Aspire.Hosting.ApplicationModel;");
        sb.AppendLine();

        // Builder class — implements IResourceBuilder<X> for each common interface
        sb.Append($"public sealed class {safeName}ResourceBuilder : SharedResourceBuilder");
        foreach (var iface in ResourceInterfaces)
        {
            sb.Append($", IResourceBuilder<{iface}>");
        }
        sb.AppendLine();
        sb.AppendLine("{");
        sb.AppendLine($"    public {safeName}ResourceBuilder(IResourceBuilder<IResource> inner, ResourceMode mode)");
        sb.AppendLine("        : base(inner, mode) { }");
        sb.AppendLine();

        // Public ApplicationBuilder property satisfies all IResourceBuilder<X>.ApplicationBuilder
        sb.AppendLine("    public IDistributedApplicationBuilder ApplicationBuilder => Inner.ApplicationBuilder;");
        sb.AppendLine();

        // Explicit interface implementations for each IResourceBuilder<X>
        foreach (var iface in ResourceInterfaces)
        {
            sb.AppendLine($"    {iface} IResourceBuilder<{iface}>.Resource => ({iface})Inner.Resource;");
            sb.AppendLine();
            sb.AppendLine($"    IResourceBuilder<{iface}> IResourceBuilder<{iface}>.WithAnnotation<TAnnotation>(TAnnotation annotation, ResourceAnnotationMutationBehavior behavior)");
            sb.AppendLine("    {");
            sb.AppendLine("        Inner.WithAnnotation(annotation, behavior);");
            sb.AppendLine("        return this;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine($"    new public {safeName}ResourceBuilder ConfigureContainer(Action<IResourceBuilder<ContainerResource>> configure)");
        sb.AppendLine("    {");
        sb.AppendLine("        base.ConfigureContainer(configure);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    new public {safeName}ResourceBuilder ConfigureProject(Action<IResourceBuilder<ProjectResource>> configure)");
        sb.AppendLine("    {");
        sb.AppendLine("        base.ConfigureProject(configure);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    new public {safeName}ResourceBuilder Configure<T>(Action<IResourceBuilder<T>> configure) where T : IResource");
        sb.AppendLine("    {");
        sb.AppendLine("        base.Configure(configure);");
        sb.AppendLine("        return this;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Extension method
        sb.AppendLine($"public static class {safeName}ResourceExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {safeName}ResourceBuilder Add{safeName}(this IDistributedApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var modeValue = builder.Configuration[\"resources:{resourceId}:mode\"];");
        sb.AppendLine("        var mode = string.Equals(modeValue, \"project\", System.StringComparison.OrdinalIgnoreCase)");
        sb.AppendLine("            ? ResourceMode.Project");
        sb.AppendLine("            : ResourceMode.Container;");
        sb.AppendLine();

        sb.AppendLine("        IResourceBuilder<IResource> inner;");
        sb.AppendLine("        if (mode == ResourceMode.Project)");
        sb.AppendLine("        {");

        var projectPath = resource.ProjectMode?.ProjectPath;
        if (!string.IsNullOrEmpty(projectPath))
        {
            sb.AppendLine($"            inner = builder.AddProject<{safeName}ProjectMetadata>(\"{resourceId}\");");
        }
        else
        {
            sb.AppendLine($"            var projectPath = builder.Configuration[\"resources:{resourceId}:projectMode:projectPath\"];");
            sb.AppendLine($"            inner = builder.AddProject(\"{resourceId}\", projectPath);");
        }

        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");

        sb.AppendLine($"            var imageName = builder.Configuration[\"resources:{resourceId}:containerMode:imageName\"] ?? \"{resourceId}\";");
        sb.AppendLine($"            var imageRegistry = builder.Configuration[\"resources:{resourceId}:containerMode:imageRegistry\"];");
        sb.AppendLine("            var image = !string.IsNullOrEmpty(imageRegistry) ? $\"{imageRegistry}/{imageName}\" : imageName;");
        sb.AppendLine($"            inner = builder.AddContainer(\"{resourceId}\", image);");

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        return new {safeName}ResourceBuilder(inner, mode);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Project metadata class if project path is known at build time
        if (!string.IsNullOrEmpty(projectPath))
        {
            sb.AppendLine();
            sb.AppendLine($"public class {safeName}ProjectMetadata : IProjectMetadata");
            sb.AppendLine("{");
            sb.AppendLine($"    public string ProjectPath => \"{projectPath}\";");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GenerateConfigurationSource(string json)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine();
        sb.AppendLine("namespace Aspire.Hosting;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registers resolved shared resources as an in-memory JSON configuration source.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SharedResourcesConfigurationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    // lang=json");
        sb.AppendLine("    private const string SharedResourcesJson = \"\"\"");

        // Indent each line of the JSON for raw string literal compatibility
        var jsonLines = json.Replace("\r", "").Split('\n');
        foreach (var line in jsonLines)
        {
            sb.Append("        ");
            sb.AppendLine(line);
        }

        sb.AppendLine("        \"\"\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds the resolved shared resources JSON to the configuration builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IConfigurationBuilder AddSharedResourcesConfiguration(this IConfigurationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var stream = new System.IO.MemoryStream(System.Text.Encoding.UTF8.GetBytes(SharedResourcesJson));");
        sb.AppendLine("        return builder.AddJsonStream(stream);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToSafeIdentifier(string name)
    {
        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }
            else
            {
                capitalizeNext = true;
            }
        }

        return sb.ToString();
    }

    private sealed class SharedResourcesConfig
    {
        public Dictionary<string, ResourceEntry> Resources { get; set; }
    }

    private sealed class ResourceEntry
    {
        public string Mode { get; set; }
        public ContainerModeEntry ContainerMode { get; set; }
        public ProjectModeEntry ProjectMode { get; set; }
    }

    private sealed class ContainerModeEntry
    {
        public string ImageName { get; set; }
        public string ImageRegistry { get; set; }
        public string BuildCommand { get; set; }
        public string BuildWorkingDirectory { get; set; }
    }

    private sealed class ProjectModeEntry
    {
        public string ProjectPath { get; set; }
    }
}