using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Spire.SourceGenerator;

/// <summary>
/// Generates type-safe builder extension methods for shared resources.
/// </summary>
[Generator]
public sealed class SharedResourceGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("SharedResources.g.json"));

        var resourceEntries = jsonFiles
            .Select(static (file, ct) => file.GetText(ct)?.ToString())
            .Where(static text => text is not null);

        context.RegisterSourceOutput(resourceEntries, static (ctx, json) =>
        {
            if (string.IsNullOrWhiteSpace(json))
                return;

            var config = InterceptorHelpers.ParseConfig(json);
            if (config?.Resources is null)
                return;

            foreach (var kvp in config.Resources)
            {
                var id = kvp.Key;
                var resource = kvp.Value;

                if (string.IsNullOrEmpty(id))
                    continue;

                var safeName = InterceptorHelpers.ToSafeIdentifier(id);
                var source = GenerateResourceSource(safeName, id, resource);

                ctx.AddSource($"{safeName}.g.cs", SourceText.From(source, Encoding.UTF8));
            }

            var configSource = GenerateConfigurationSource(json);
            ctx.AddSource("SharedResourcesConfiguration.g.cs", SourceText.From(configSource, Encoding.UTF8));
        });
    }

    private static string GenerateResourceSource(string safeName, string resourceId, ResourceEntry resource)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using Aspire.Hosting;");
        sb.AppendLine("using Aspire.Hosting.ApplicationModel;");
        sb.AppendLine();

        // Resource type — extends SharedResource
        sb.AppendLine($"public sealed class {safeName}Resource : SharedResource");
        sb.AppendLine("{");
        sb.AppendLine($"    public {safeName}Resource(IResource inner, ResourceMode mode, IResourceBuilder<IResource> innerBuilder)");
        sb.AppendLine("        : base(inner, mode, innerBuilder) { }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Extension method
        sb.AppendLine($"public static class {safeName}ResourceExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IResourceBuilder<{safeName}Resource> Add{safeName}(this IDistributedApplicationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var modeValue = builder.Configuration[\"resources:{resourceId}:mode\"];");
        sb.AppendLine("        var mode = string.Equals(modeValue, \"project\", System.StringComparison.OrdinalIgnoreCase)");
        sb.AppendLine("            ? ResourceMode.Project");
        sb.AppendLine("            : ResourceMode.Container;");
        sb.AppendLine();

        sb.AppendLine("        IResourceBuilder<IResource> inner;");
        sb.AppendLine("        if (mode == ResourceMode.Project)");
        sb.AppendLine("        {");

        var projectPath = resource.ProjectMode?.ProjectPath;
        if (!string.IsNullOrEmpty(projectPath))
        {
            sb.AppendLine($"            inner = builder.AddProject<{safeName}ProjectMetadata>(\"{resourceId}\");");
        }
        else
        {
            sb.AppendLine($"            var projectPath = builder.Configuration[\"resources:{resourceId}:projectMode:projectPath\"];");
            sb.AppendLine($"            inner = builder.AddProject(\"{resourceId}\", projectPath);");
        }

        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");

        sb.AppendLine($"            var imageName = builder.Configuration[\"resources:{resourceId}:containerMode:imageName\"] ?? \"{resourceId}\";");
        sb.AppendLine($"            var containerBuilder = builder.AddContainer(\"{resourceId}\", imageName);");
        sb.AppendLine();
        sb.AppendLine($"            var imageRegistry = builder.Configuration[\"resources:{resourceId}:containerMode:imageRegistry\"];");
        sb.AppendLine("            if (!string.IsNullOrEmpty(imageRegistry))");
        sb.AppendLine("                containerBuilder = containerBuilder.WithImageRegistry(imageRegistry);");
        sb.AppendLine();
        sb.AppendLine($"            var imageTag = builder.Configuration[\"resources:{resourceId}:containerMode:imageTag\"];");
        sb.AppendLine("            if (!string.IsNullOrEmpty(imageTag))");
        sb.AppendLine("                containerBuilder = containerBuilder.WithImageTag(imageTag);");
        sb.AppendLine();
        sb.AppendLine($"            var buildWorkingDirectory = builder.Configuration[\"resources:{resourceId}:containerMode:buildWorkingDirectory\"] ?? \".\";");
        sb.AppendLine($"            var sync = builder.AddExecutable(\"{resourceId}-image-sync\", \"spire\", buildWorkingDirectory, \"build\", \"--ids\", \"{resourceId}\");");
        sb.AppendLine("            sync.WithParentRelationship(containerBuilder);");
        sb.AppendLine("            containerBuilder.WaitForCompletion(sync);");
        sb.AppendLine($"            inner = containerBuilder;");

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        var resource = new {safeName}Resource(inner.Resource, mode, inner);");
        sb.AppendLine($"        return new SharedResourceBuilder<{safeName}Resource>(inner, resource);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Project metadata class if project path is known at build time
        if (!string.IsNullOrEmpty(projectPath))
        {
            sb.AppendLine();
            sb.AppendLine($"public class {safeName}ProjectMetadata : IProjectMetadata");
            sb.AppendLine("{");
            sb.AppendLine($"    public string ProjectPath => \"{projectPath}\";");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GenerateConfigurationSource(string json)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine();
        sb.AppendLine("namespace Aspire.Hosting;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registers resolved shared resources as an in-memory JSON configuration source.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SharedResourcesConfigurationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    // lang=json");
        sb.AppendLine("    private const string SharedResourcesJson = \"\"\"");

        // Indent each line of the JSON for raw string literal compatibility
        var jsonLines = json.Replace("\r", "").Split('\n');
        foreach (var line in jsonLines)
        {
            sb.Append("        ");
            sb.AppendLine(line);
        }

        sb.AppendLine("        \"\"\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds the resolved shared resources JSON to the configuration builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IConfigurationBuilder AddSharedResourcesConfiguration(this IConfigurationBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var stream = new System.IO.MemoryStream(System.Text.Encoding.UTF8.GetBytes(SharedResourcesJson));");
        sb.AppendLine("        return builder.AddJsonStream(stream);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
